config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :basvurans

  resources :form_birs

  resources :gonullus

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/form_bir.rb
class FormBir < ActiveRecord::Base
  belongs_to :basvuran
  belongs_to :gonullu
  belongs_to :user
  has_one :user
  has_one :gonullu
  has_one :option_destek_aliyor
  has_one :option_iletisime_gecen
  has_one :option_iletisime_gecme_yolu
  has_many :siginak_giris_cikis
end

app/controllers/form_birs_controller.rb
class FormBirsController < ApplicationController
  before_action :set_form_bir, only: [:show, :edit, :update, :destroy]

  # GET /form_birs
  # GET /form_birs.json
  def index
    @form_birs = FormBir.all
  end

  # GET /form_birs/1
  # GET /form_birs/1.json
  def show
  end

  # GET /form_birs/new
  def new
    @form_bir = FormBir.new
  end

  # GET /form_birs/1/edit
  def edit
  end

  # POST /form_birs
  # POST /form_birs.json
  def create
    @form_bir = FormBir.new(form_bir_params)

    respond_to do |format|
      if @form_bir.save
        format.html { redirect_to @form_bir, notice: 'Form bir was successfully created.' }
        format.json { render :show, status: :created, location: @form_bir }
      else
        format.html { render :new }
        format.json { render json: @form_bir.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_birs/1
  # PATCH/PUT /form_birs/1.json
  def update
    respond_to do |format|
      if @form_bir.update(form_bir_params)
        format.html { redirect_to @form_bir, notice: 'Form bir was successfully updated.' }
        format.json { render :show, status: :ok, location: @form_bir }
      else
        format.html { render :edit }
        format.json { render json: @form_bir.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_birs/1
  # DELETE /form_birs/1.json
  def destroy
    @form_bir.destroy
    respond_to do |format|
      format.html { redirect_to form_birs_url, notice: 'Form bir was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_bir
      @form_bir = FormBir.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_bir_params
      params.require(:form_bir).permit(:basvuran_id, :ilk_basvuru_tarihi, :notlar, :mc_siginaginda_kaliyor, :gonullu_id, :user_id)
    end
end

app/helpers/form_birs_helper.rb
module FormBirsHelper
end

app/views/form_birs/_form.html.erb
<%= form_for @form_bir, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :ilk_basvuru_tarihi, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :ilk_basvuru_tarihi, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :notlar, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :notlar, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mc_siginaginda_kaliyor, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :mc_siginaginda_kaliyor, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  form_birs_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/form_birs/edit.html.erb
<%- model_class = FormBir -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => FormBir %></h1>
</div>
<%= render :partial => 'form' %>

app/views/form_birs/index.html.erb
<%- model_class = FormBir -%>
<div class="page-header">
  <h1><%=t '.title', :default => FormBir %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:ilk_basvuru_tarihi) %></th>
      <th><%= model_class.human_attribute_name(:notlar) %></th>
      <th><%= model_class.human_attribute_name(:mc_siginaginda_kaliyor) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @form_birs.each do |form_bir| %>
      <tr>
        <td><%= form_bir.id %></td>
        <td><%= form_bir.ilk_basvuru_tarihi %></td>
        <td><%= form_bir.notlar %></td>
        <td><%= form_bir.mc_siginaginda_kaliyor %></td>
        <td><%=l form_bir.created_at, format: :long %></td>
        <td>
          <%= link_to form_bir_path(form_bir), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to form_bir_path(form_bir), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_form_bir_path,
            :class => 'btn btn-primary' %>

app/views/form_birs/new.html.erb
<%- model_class = FormBir -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => FormBir %></h1>
</div>
<%= render :partial => 'form' %>

app/views/form_birs/show.html.erb
<%- model_class = FormBir -%>
<div class="page-header">
  <h1><%=t '.title', :default => FormBir %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ilk_basvuru_tarihi) %></dt>
      <dd><pre class="prettyprint"><%= @form_bir.ilk_basvuru_tarihi %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:notlar) %></dt>
      <dd><pre class="prettyprint"><%= @form_bir.notlar %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:mc_siginaginda_kaliyor) %></dt>
      <dd><pre class="prettyprint"><%= @form_bir.mc_siginaginda_kaliyor %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              form_birs_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_form_bir_path(@form_bir), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              form_bir_path(@form_bir),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>